"""Generated tool configuration for Codex and Claude Code."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List

import yaml

from .config import AgentConfig, MCPServerConfig, SkillConfig, SoloConfig
from .project import SoloProject


GENERATED_MARKER = "Generated by solo tooling sync"


@dataclass
class ToolingSyncResult:
    """Summary of generated tooling files."""

    written: List[str] = field(default_factory=list)
    skipped: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ok": self.ok,
            "written": self.written,
            "skipped": self.skipped,
            "errors": self.errors,
        }


@dataclass
class ToolingDoctorResult:
    """Health report for generated tooling files."""

    ok: bool
    checked: List[str] = field(default_factory=list)
    missing: List[str] = field(default_factory=list)
    unmanaged: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "ok": self.ok,
            "checked": self.checked,
            "missing": self.missing,
            "unmanaged": self.unmanaged,
            "errors": self.errors,
        }


def sync_tooling(project: SoloProject, target: str = "all", force: bool = False) -> ToolingSyncResult:
    """Render generated child-agent tooling files from .solo config."""

    config = project.require_config()
    manifest = _load_manifest(project)
    targets = _resolve_targets(manifest, target)
    result = ToolingSyncResult()

    if "codex" in targets:
        _write_codex(project, config, manifest, result, force)
    if "claude" in targets:
        _write_claude(project, config, manifest, result, force)

    return result


def doctor_tooling(project: SoloProject, target: str = "all") -> ToolingDoctorResult:
    """Check whether generated tooling files are present and managed."""

    errors: List[str] = []
    try:
        manifest = _load_manifest(project)
        targets = _resolve_targets(manifest, target)
    except ValueError as exc:
        return ToolingDoctorResult(ok=False, errors=[str(exc)])

    expected = _expected_paths(project, manifest, targets)
    checked: List[str] = []
    missing: List[str] = []
    unmanaged: List[str] = []
    for path in expected:
        display = _display_path(project, path)
        checked.append(display)
        if not path.exists():
            missing.append(display)
            continue
        if not _is_generated(path):
            unmanaged.append(display)

    return ToolingDoctorResult(
        ok=not missing and not unmanaged and not errors,
        checked=checked,
        missing=missing,
        unmanaged=unmanaged,
        errors=errors,
    )


def _write_codex(project: SoloProject, config: SoloConfig, manifest: Dict[str, Any], result: ToolingSyncResult, force: bool) -> None:
    codex = manifest.get("targets", {}).get("codex", {})
    agents_md = project.path / codex.get("agents_md", "AGENTS.md")
    codex_config = project.path / codex.get("config", ".solo/generated/codex/default/config.toml")
    commands_dir = project.path / codex.get("commands_dir", ".solo/generated/codex/default/commands")
    _write_generated(project, agents_md, _render_memory(project, config, manifest, "Codex"), result, force)
    _write_generated(project, codex_config, _render_codex_config(config), result, force)
    _write_commands(project, manifest, commands_dir, result, force)


def _write_claude(project: SoloProject, config: SoloConfig, manifest: Dict[str, Any], result: ToolingSyncResult, force: bool) -> None:
    claude = manifest.get("targets", {}).get("claude", {})
    root_memory = project.path / claude.get("root_memory", "CLAUDE.md")
    project_memory = project.path / claude.get("project_memory", ".claude/CLAUDE.md")
    settings = project.path / claude.get("settings", ".claude/settings.json")
    agents_dir = project.path / claude.get("agents_dir", ".claude/agents")
    skills_dir = project.path / claude.get("skills_dir", ".claude/skills")
    commands_dir = project.path / claude.get("commands_dir", ".claude/commands")
    mcp = project.path / claude.get("mcp", ".mcp.json")

    memory = _render_memory(project, config, manifest, "Claude Code")
    _write_generated(project, root_memory, memory, result, force)
    _write_generated(project, project_memory, memory, result, force)
    _write_generated(project, settings, _render_claude_settings(), result, force)
    _write_generated(project, mcp, _render_mcp_json(config), result, force)

    agent_names = _profile_values(manifest, "agents") or list(config.agents.keys())
    for role in agent_names:
        if role not in config.agents:
            continue
        _write_generated(project, agents_dir / f"{role}.md", _render_agent(project, config, role), result, force)

    skill_names = _profile_values(manifest, "skills") or list(config.skills.keys())
    for name in skill_names:
        if name not in config.skills:
            continue
        _write_generated(project, skills_dir / name / "SKILL.md", _render_skill(project, config.skills[name], name), result, force)

    _write_commands(project, manifest, commands_dir, result, force)


def _load_manifest(project: SoloProject) -> Dict[str, Any]:
    path = project.solo_dir / "tooling" / "manifest.yaml"
    if not path.exists():
        raise ValueError(f"Missing tooling manifest: {_display_path(project, path)}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Invalid tooling manifest: {_display_path(project, path)}")
    return data


def _resolve_targets(manifest: Dict[str, Any], target: str) -> List[str]:
    known = manifest.get("targets", {})
    if target == "all":
        return [name for name, data in known.items() if data.get("enabled", True)]
    if target not in known:
        raise ValueError(f"Unknown tooling target: {target}")
    if not known[target].get("enabled", True):
        return []
    return [target]


def _profile_values(manifest: Dict[str, Any], key: str) -> List[str]:
    default = manifest.get("profiles", {}).get("default", {})
    values = default.get(key, [])
    return [str(value) for value in values]


def _write_commands(project: SoloProject, manifest: Dict[str, Any], commands_dir: Path, result: ToolingSyncResult, force: bool) -> None:
    for name, command in sorted(manifest.get("commands", {}).items()):
        data = command if isinstance(command, dict) else {"description": str(command)}
        source_path = project.solo_dir / str(data.get("path", ""))
        if source_path.exists():
            body = source_path.read_text(encoding="utf-8").strip()
        else:
            body = str(data.get("description", "")).strip()
        content = "\n".join([_markdown_marker(), body, ""])
        _write_generated(project, commands_dir / f"{name}.md", content, result, force)


def _render_memory(project: SoloProject, config: SoloConfig, manifest: Dict[str, Any], target_name: str) -> str:
    lines = [
        _markdown_marker(),
        f"# {config.project.name} Agent Instructions",
        "",
        f"These instructions are generated for {target_name} from `.solo/tooling/manifest.yaml` and `.solo/config.yaml`.",
        "Run `solo setup tooling sync` after changing Solo agent, provider, MCP, skill, or tooling manifest settings.",
        "",
    ]
    if config.project.description:
        lines.extend(["## Project", "", config.project.description, ""])

    rules = _render_rules(project, manifest)
    if rules:
        lines.extend(["## Shared Rules", "", rules, ""])

    lines.extend(["## Agent Routing", ""])
    for role, agent in sorted(config.agents.items()):
        lines.extend(_agent_summary_lines(role, agent))
        lines.append("")

    lines.extend(["## MCP Servers", ""])
    if config.mcp_servers:
        for name, server in sorted(config.mcp_servers.items()):
            status = "enabled" if server.enabled else "disabled"
            description = f" - {server.description}" if server.description else ""
            lines.append(f"- `{name}`: {status}; command `{server.command}`{description}")
    else:
        lines.append("- No MCP servers configured.")
    lines.append("")

    lines.extend(["## Skills", ""])
    if config.skills:
        for name, skill in sorted(config.skills.items()):
            lines.append(f"- `{name}`: {skill.description} (`.solo/{skill.path}`)")
    else:
        lines.append("- No skills configured.")
    lines.append("")

    commands = manifest.get("commands", {})
    if commands:
        lines.extend(["## Solo Commands", ""])
        for name, command in sorted(commands.items()):
            data = command if isinstance(command, dict) else {"description": str(command)}
            lines.append(f"- `{name}`: {data.get('description', '')}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_rules(project: SoloProject, manifest: Dict[str, Any]) -> str:
    chunks: List[str] = []
    for item in manifest.get("rules", []):
        rel = str(item.get("path", ""))
        if not rel:
            continue
        source = project.solo_dir / rel
        if source.exists():
            chunks.append(source.read_text(encoding="utf-8").strip())
    return "\n\n".join(chunk for chunk in chunks if chunk)


def _agent_summary_lines(role: str, agent: AgentConfig) -> List[str]:
    lines = [
        f"- `{role}`: provider `{agent.provider}`, model `{agent.model}`",
        f"  - runtime: `{agent.runtime or 'project default'}`",
        f"  - skills: {', '.join(f'`{skill}`' for skill in agent.skills) if agent.skills else '-'}",
        f"  - mcp: {', '.join(f'`{server}`' for server in agent.mcp_servers) if agent.mcp_servers else '-'}",
        f"  - tools: {', '.join(f'`{tool}`' for tool in agent.tools) if agent.tools else '-'}",
    ]
    return lines


def _render_agent(project: SoloProject, config: SoloConfig, role: str) -> str:
    agent = config.agents[role]
    prompt_path = project.solo_dir / "agents" / f"{role}.md"
    prompt = prompt_path.read_text(encoding="utf-8").strip() if prompt_path.exists() else ""
    lines = [
        _markdown_marker(),
        f"# {role} Agent",
        "",
        f"Provider: `{agent.provider}`",
        f"Model: `{agent.model}`",
        f"Runtime: `{agent.runtime or 'project default'}`",
        f"Temperature: `{agent.temperature}`",
        f"Max tokens: `{agent.max_tokens}`",
        f"Skills: {', '.join(f'`{skill}`' for skill in agent.skills) if agent.skills else '-'}",
        f"MCP servers: {', '.join(f'`{server}`' for server in agent.mcp_servers) if agent.mcp_servers else '-'}",
        f"Tools: {', '.join(f'`{tool}`' for tool in agent.tools) if agent.tools else '-'}",
        "",
        "## Solo Role Prompt",
        "",
        prompt or "No role prompt found.",
        "",
    ]
    return "\n".join(lines)


def _render_skill(project: SoloProject, skill: SkillConfig, name: str) -> str:
    source = project.solo_dir / skill.path
    body = source.read_text(encoding="utf-8").strip() if source.exists() else skill.description
    return "\n".join(
        [
            _markdown_marker(),
            f"# {name}",
            "",
            f"Description: {skill.description}",
            "",
            body,
            "",
        ]
    )


def _render_claude_settings() -> str:
    return json.dumps(
        {
            "_comment": GENERATED_MARKER,
            "includeCoAuthoredBy": False,
            "permissions": {"allow": [], "deny": []},
            "env": {},
        },
        indent=2,
        sort_keys=True,
    ) + "\n"


def _render_mcp_json(config: SoloConfig) -> str:
    servers = {
        name: _mcp_server_payload(server)
        for name, server in sorted(config.mcp_servers.items())
        if server.enabled
    }
    return json.dumps({"_comment": GENERATED_MARKER, "mcpServers": servers}, indent=2, sort_keys=True) + "\n"


def _mcp_server_payload(server: MCPServerConfig) -> Dict[str, Any]:
    payload: Dict[str, Any] = {"command": server.command}
    if server.args:
        payload["args"] = server.args
    if server.env:
        payload["env"] = server.env
    return payload


def _render_codex_config(config: SoloConfig) -> str:
    lines = [
        f"# {GENERATED_MARKER}",
        "# Source: .solo/config.yaml",
        "",
    ]
    enabled = [(name, server) for name, server in sorted(config.mcp_servers.items()) if server.enabled]
    if not enabled:
        lines.append("# No enabled MCP servers. Enable one with `solo setup mcp <name> --enable`.")
        return "\n".join(lines).rstrip() + "\n"

    for name, server in enabled:
        lines.extend(
            [
                f"[mcp_servers.{name}]",
                f"command = {_toml_string(server.command)}",
            ]
        )
        if server.args:
            lines.append(f"args = {_toml_array(server.args)}")
        if server.env:
            entries = ", ".join(f"{key} = {_toml_string(value)}" for key, value in sorted(server.env.items()))
            lines.append(f"env = {{ {entries} }}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _write_generated(project: SoloProject, path: Path, content: str, result: ToolingSyncResult, force: bool) -> None:
    display = _display_path(project, path)
    if path.exists() and not force and not _is_generated(path):
        result.skipped.append(display)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    result.written.append(display)


def _expected_paths(project: SoloProject, manifest: Dict[str, Any], targets: Iterable[str]) -> List[Path]:
    expected: List[Path] = []
    target_data = manifest.get("targets", {})
    if "codex" in targets:
        codex = target_data.get("codex", {})
        expected.append(project.path / codex.get("agents_md", "AGENTS.md"))
        expected.append(project.path / codex.get("config", ".solo/generated/codex/default/config.toml"))
        commands_dir = project.path / codex.get("commands_dir", ".solo/generated/codex/default/commands")
        for command in manifest.get("commands", {}):
            expected.append(commands_dir / f"{command}.md")
    if "claude" in targets:
        claude = target_data.get("claude", {})
        expected.append(project.path / claude.get("root_memory", "CLAUDE.md"))
        expected.append(project.path / claude.get("project_memory", ".claude/CLAUDE.md"))
        expected.append(project.path / claude.get("settings", ".claude/settings.json"))
        expected.append(project.path / claude.get("mcp", ".mcp.json"))
        agents_dir = project.path / claude.get("agents_dir", ".claude/agents")
        skills_dir = project.path / claude.get("skills_dir", ".claude/skills")
        commands_dir = project.path / claude.get("commands_dir", ".claude/commands")
        for role in _profile_values(manifest, "agents"):
            expected.append(agents_dir / f"{role}.md")
        for skill in _profile_values(manifest, "skills"):
            expected.append(skills_dir / skill / "SKILL.md")
        for command in manifest.get("commands", {}):
            expected.append(commands_dir / f"{command}.md")
    return expected


def _display_path(project: SoloProject, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(project.path))
    except ValueError:
        return str(path)


def _is_generated(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8")[:500]
    except UnicodeDecodeError:
        return False
    return GENERATED_MARKER in head


def _markdown_marker() -> str:
    return f"<!-- {GENERATED_MARKER}. Source: .solo/tooling/manifest.yaml -->"


def _toml_string(value: str) -> str:
    return json.dumps(value)


def _toml_array(values: Iterable[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"
